name: jsproxyize
description: A starting point for Dart libraries or applications.
version: 0.0.2
author: Adam Stark <llamadonica@gmail.com>
homepage: https://github.com/llamadonica/jsproxyize

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  polymer: ^1.0.0-rc.15
  analyzer: any
  code_transformers: ^0.3.1
  barback: ^0.15.2
  source_maps: ^0.10.1
  path: ^1.3.9

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
